create table if not exists genre --*
(
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists mpa --*
(
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists user --*
(
    id       bigint generated by default as identity primary key,
    login    varchar(255) not null,
    name     varchar(255),
    email    varchar(255) not null
    birthday date         not null,
);

create table if not exists friendship --*
(
    user_id   bigint,
    friend_id bigint,
    difference bigint,
    foreign key (user_id) references user (id) on delete cascade,
    foreign key (friend_id) references user (id) on delete cascade,
    primary key (user_id, friend_id)
);

create table if not exists film --*
(
    id           bigint generated by default as identity primary key,
    name         varchar(255) not null,
    description  varchar(200),
    release_date date,
    duration     int,
    mpa_id       int,
    foreign key (mpa_id) references mpa (id) on delete cascade
);

create table if not exists like --*
(
    film_id bigint,
    user_id bigint,
    foreign key (film_id) references film (id) on delete cascade,
    foreign key (user_id) references user (id) on delete cascade,
    primary key (film_id, user_id)
);


create table if not exists film_genre --*
(
    film_id  bigint,
    genre_id int,
    foreign key (film_id) references film (id) on delete cascade,
    foreign key (genre_id) references genre (id) on delete cascade,
    primary key (film_id, genre_id)
);
